// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// between_num
LogicalVector between_num(NumericVector x, NumericVector from, NumericVector to, bool left_closed, bool right_closed);
RcppExport SEXP _bedrock_between_num(SEXP xSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP left_closedSEXP, SEXP right_closedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< bool >::type left_closed(left_closedSEXP);
    Rcpp::traits::input_parameter< bool >::type right_closed(right_closedSEXP);
    rcpp_result_gen = Rcpp::wrap(between_num(x, from, to, left_closed, right_closed));
    return rcpp_result_gen;
END_RCPP
}
// binaryTree_cpp
Rcpp::IntegerVector binaryTree_cpp(int n);
RcppExport SEXP _bedrock_binaryTree_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(binaryTree_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// conv_DecToBin
CharacterVector conv_DecToBin(IntegerVector n);
RcppExport SEXP _bedrock_conv_DecToBin(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(conv_DecToBin(n));
    return rcpp_result_gen;
END_RCPP
}
// is_prime_u64
bool is_prime_u64(double x);
RcppExport SEXP _bedrock_is_prime_u64(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(is_prime_u64(x));
    return rcpp_result_gen;
END_RCPP
}
// primes_upto
IntegerVector primes_upto(int n);
RcppExport SEXP _bedrock_primes_upto(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(primes_upto(n));
    return rcpp_result_gen;
END_RCPP
}
// factor_u64
NumericMatrix factor_u64(double x);
RcppExport SEXP _bedrock_factor_u64(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(factor_u64(x));
    return rcpp_result_gen;
END_RCPP
}
// pip_cpp
IntegerVector pip_cpp(NumericVector ptx, NumericVector pty, NumericVector plx, NumericVector ply);
RcppExport SEXP _bedrock_pip_cpp(SEXP ptxSEXP, SEXP ptySEXP, SEXP plxSEXP, SEXP plySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ptx(ptxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pty(ptySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plx(plxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ply(plySEXP);
    rcpp_result_gen = Rcpp::wrap(pip_cpp(ptx, pty, plx, ply));
    return rcpp_result_gen;
END_RCPP
}
// roman2int_cpp
IntegerVector roman2int_cpp(CharacterVector x);
RcppExport SEXP _bedrock_roman2int_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(roman2int_cpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bedrock_between_num", (DL_FUNC) &_bedrock_between_num, 5},
    {"_bedrock_binaryTree_cpp", (DL_FUNC) &_bedrock_binaryTree_cpp, 1},
    {"_bedrock_conv_DecToBin", (DL_FUNC) &_bedrock_conv_DecToBin, 1},
    {"_bedrock_is_prime_u64", (DL_FUNC) &_bedrock_is_prime_u64, 1},
    {"_bedrock_primes_upto", (DL_FUNC) &_bedrock_primes_upto, 1},
    {"_bedrock_factor_u64", (DL_FUNC) &_bedrock_factor_u64, 1},
    {"_bedrock_pip_cpp", (DL_FUNC) &_bedrock_pip_cpp, 4},
    {"_bedrock_roman2int_cpp", (DL_FUNC) &_bedrock_roman2int_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_bedrock(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
