// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// as_cdate_fmt_cpp
std::string as_cdate_fmt_cpp(std::string fmt);
RcppExport SEXP _bedrock_as_cdate_fmt_cpp(SEXP fmtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fmt(fmtSEXP);
    rcpp_result_gen = Rcpp::wrap(as_cdate_fmt_cpp(fmt));
    return rcpp_result_gen;
END_RCPP
}
// between_num_cpp
LogicalVector between_num_cpp(NumericVector x, NumericVector from, NumericVector to, bool left_closed, bool right_closed);
RcppExport SEXP _bedrock_between_num_cpp(SEXP xSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP left_closedSEXP, SEXP right_closedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< bool >::type left_closed(left_closedSEXP);
    Rcpp::traits::input_parameter< bool >::type right_closed(right_closedSEXP);
    rcpp_result_gen = Rcpp::wrap(between_num_cpp(x, from, to, left_closed, right_closed));
    return rcpp_result_gen;
END_RCPP
}
// binary_tree_cpp
Rcpp::IntegerVector binary_tree_cpp(int n);
RcppExport SEXP _bedrock_binary_tree_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(binary_tree_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// dec_to_bin_cpp
CharacterVector dec_to_bin_cpp(IntegerVector n);
RcppExport SEXP _bedrock_dec_to_bin_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(dec_to_bin_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// is_prime_cpp
bool is_prime_cpp(double x);
RcppExport SEXP _bedrock_is_prime_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(is_prime_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// primes_upto_cpp
IntegerVector primes_upto_cpp(int n);
RcppExport SEXP _bedrock_primes_upto_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(primes_upto_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// factor_u64_cpp
NumericMatrix factor_u64_cpp(double x);
RcppExport SEXP _bedrock_factor_u64_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(factor_u64_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// pip_cpp
IntegerVector pip_cpp(NumericVector ptx, NumericVector pty, NumericVector plx, NumericVector ply);
RcppExport SEXP _bedrock_pip_cpp(SEXP ptxSEXP, SEXP ptySEXP, SEXP plxSEXP, SEXP plySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ptx(ptxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pty(ptySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type plx(plxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ply(plySEXP);
    rcpp_result_gen = Rcpp::wrap(pip_cpp(ptx, pty, plx, ply));
    return rcpp_result_gen;
END_RCPP
}
// roman_to_int_cpp
IntegerVector roman_to_int_cpp(CharacterVector x);
RcppExport SEXP _bedrock_roman_to_int_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(roman_to_int_cpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bedrock_as_cdate_fmt_cpp", (DL_FUNC) &_bedrock_as_cdate_fmt_cpp, 1},
    {"_bedrock_between_num_cpp", (DL_FUNC) &_bedrock_between_num_cpp, 5},
    {"_bedrock_binary_tree_cpp", (DL_FUNC) &_bedrock_binary_tree_cpp, 1},
    {"_bedrock_dec_to_bin_cpp", (DL_FUNC) &_bedrock_dec_to_bin_cpp, 1},
    {"_bedrock_is_prime_cpp", (DL_FUNC) &_bedrock_is_prime_cpp, 1},
    {"_bedrock_primes_upto_cpp", (DL_FUNC) &_bedrock_primes_upto_cpp, 1},
    {"_bedrock_factor_u64_cpp", (DL_FUNC) &_bedrock_factor_u64_cpp, 1},
    {"_bedrock_pip_cpp", (DL_FUNC) &_bedrock_pip_cpp, 4},
    {"_bedrock_roman_to_int_cpp", (DL_FUNC) &_bedrock_roman_to_int_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_bedrock(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
