
#' Extract Documentation Concepts from a Package
#'
#' Scans the Rd database of a package and returns all \code{\\concept}
#' entries, optionally filtered by a prefix.
#'
#' This function relies on the Rd concept entries generated by roxygen2
#' from \code{@concept} tags.
#'
#' @param pkg Character string. Name of an installed package.
#' @param prefix Optional character string. If given, only concepts
#'   starting with this prefix are returned, with the prefix removed.
#' @param sorted Logical. If \code{TRUE} (default), concepts are returned
#'   sorted.
#'
#' @return A character vector of unique concept names.
#'
#' @keywords internal
#' @noRd
getConcepts <- function(pkg, prefix = NULL, sorted = TRUE) {

  rdDb <- tools::Rd_db(pkg)

  concepts <- unlist(lapply(rdDb, function(rd) {

    nodes <- Filter(
      function(x) identical(attr(x, "Rd_tag"), "\\concept"),
      rd
    )

    if (length(nodes) > 0)
      unlist(lapply(nodes, as.character))
  }))

  if (length(concepts) == 0)
    return(character(0))

  if (!is.null(prefix)) {
    concepts <- concepts[startsWith(concepts, prefix)]
    concepts <- substring(concepts, nchar(prefix) + 1L)
  }

  concepts <- unique(concepts)

  if (sorted)
    concepts <- sort(concepts)

  concepts
}
