
#' Extract documentation topics from a package
#'
#' Scans the Rd database of a package and returns all documentation
#' concepts that follow the naming scheme `topic.*`.
#'
#' Topics are expected to be defined via:
#' \preformatted{
#' }
#'
#' The returned values have the `topic.` prefix removed.
#'
#' @param pkg Character string. Name of an installed package.
#' @param sort Logical. If TRUE (default), topics are returned sorted.
#'
#' @return A character vector of unique topic names.
#'
#' @details
#' This function relies on the Rd concept entries generated by roxygen2.
#' the Rd files, topics must follow a unique prefix convention
#' (e.g., `topic.*`) to be distinguishable.
#'
#' @keywords internal
#' @noRd
#' @family pkg.introspection
#' @concept package-utilities
#' @concept data-inspection
getTopics <- function(pkg, sort = TRUE) {
  
  rd_db <- tools::Rd_db(pkg)
  
  concepts <- unlist(lapply(rd_db, function(rd) {
    
    nodes <- Filter(function(x)
      attr(x, "Rd_tag") == "\\concept",
      rd)
    
    if (length(nodes) > 0)
      unlist(lapply(nodes, as.character))
  }))
  
  if (length(concepts) == 0)
    return(character(0))
  
  topics <- concepts[startsWith(concepts, "topic.")]
  
  if (length(topics) == 0)
    return(character(0))
  
  topics <- sub("^topic\\.", "", topics)
  topics <- unique(topics)
  
  if (sort)
    topics <- sort(topics)
  
  topics
}
