# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

as_CDateFmt_cpp <- function(fmt) {
    .Call(`_bedrock_as_CDateFmt_cpp`, fmt)
}

between_num <- function(x, from, to, left_closed = TRUE, right_closed = TRUE) {
    .Call(`_bedrock_between_num`, x, from, to, left_closed, right_closed)
}

binaryTree_cpp <- function(n) {
    .Call(`_bedrock_binaryTree_cpp`, n)
}

conv_DecToBin <- function(n) {
    .Call(`_bedrock_conv_DecToBin`, n)
}

is_prime_u64 <- function(x) {
    .Call(`_bedrock_is_prime_u64`, x)
}

primes_upto <- function(n) {
    .Call(`_bedrock_primes_upto`, n)
}

factor_u64 <- function(x) {
    .Call(`_bedrock_factor_u64`, x)
}

pip_cpp <- function(ptx, pty, plx, ply) {
    .Call(`_bedrock_pip_cpp`, ptx, pty, plx, ply)
}

roman2int_cpp <- function(x) {
    .Call(`_bedrock_roman2int_cpp`, x)
}

