# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

as_cdate_fmt_cpp <- function(fmt) {
    .Call(`_bedrock_as_cdate_fmt_cpp`, fmt)
}

between_num_cpp <- function(x, from, to, left_closed = TRUE, right_closed = TRUE) {
    .Call(`_bedrock_between_num_cpp`, x, from, to, left_closed, right_closed)
}

binary_tree_cpp <- function(n) {
    .Call(`_bedrock_binary_tree_cpp`, n)
}

dec_to_bin_cpp <- function(n) {
    .Call(`_bedrock_dec_to_bin_cpp`, n)
}

is_prime_cpp <- function(x) {
    .Call(`_bedrock_is_prime_cpp`, x)
}

primes_upto_cpp <- function(n) {
    .Call(`_bedrock_primes_upto_cpp`, n)
}

factor_u64_cpp <- function(x) {
    .Call(`_bedrock_factor_u64_cpp`, x)
}

pip_cpp <- function(ptx, pty, plx, ply) {
    .Call(`_bedrock_pip_cpp`, ptx, pty, plx, ply)
}

roman_to_int_cpp <- function(x) {
    .Call(`_bedrock_roman_to_int_cpp`, x)
}

